apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: nodeport
      port: 30082
      targetPort: 80
      nodePort: 30082
  type: NodePort
 